[server]
headless = true
port = 5731
sslCertFile = '.streamlit/ssl/certchain.pem'
sslKeyFile = '.streamlit/ssl/private.key'



[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"